//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        public int ID_Contrat { get; set; }
        public string Date_D_Contrat { get; set; }
        public Nullable<int> Nombre_Jours { get; set; }
        public string Date_F_Contrat { get; set; }
        public Nullable<int> ID_voiture { get; set; }
        public Nullable<int> ID_client { get; set; }
        public string Réglement { get; set; }
        public Nullable<int> PrixPar_Jour { get; set; }
        public Nullable<int> Montant { get; set; }
        public Nullable<int> Paiement { get; set; }
        public Nullable<int> Reste { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Voiture Voiture { get; set; }
    }
}
